const WALLETS_UPDATE = 'app/wallets/UPDATE';
const WALLETS_UPDATE_ONE = 'app/wallets/UPDATE_ONE';
const WALLETS_SELECT = 'app/wallets/SELECT';
const WALLETS_ERROR = 'app/wallets/ERROR';

export { WALLETS_UPDATE, WALLETS_SELECT, WALLETS_ERROR, WALLETS_UPDATE_ONE };
