const ATTRIBUTES_UPDATE = 'app/attributes/UPDATE';
const ATTRIBUTES_DISALLOW = 'app/attributes/DISALLOW';
const ATTRIBUTES_SET_LOADING = 'app/attributes/SET_LOADING';
const ATTRIBUTES_OPTION_SELECT = 'app/attributes/OPTION_SELECT';

export { ATTRIBUTES_UPDATE, ATTRIBUTES_SET_LOADING, ATTRIBUTES_DISALLOW, ATTRIBUTES_OPTION_SELECT };
